import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
// import Swiper core and required modules
import { Navigation, A11y, Autoplay  } from 'swiper';
import { Swiper, SwiperSlide  } from 'swiper/react';
// import ProgressBar from 'react-bootstrap/ProgressBar';
// import { useTimer } from 'react-timer-hook';
// import { useRef } from 'react';
import ProductCarousel from '@/components/ProductCarousel'
import MainBanner from '@/components/MainBanner'

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';


// function MyTimer({ expiryTimestamp }) {
//   const {
//     seconds,
//     minutes,
//     hours,
//     days,
//     // isRunning,
//   } = useTimer({ expiryTimestamp, onExpire: () => console.warn('onExpire called') });


//   return (
//     <div style={{textAlign: 'center'}}>
//       <div className='timer-div'>
//         <span>{days}</span>:<span>{hours}</span>:<span>{minutes}</span>:<span>{seconds}</span>
//       </div>
//       {/* <p>{isRunning ? 'Running' : 'Not running'}</p> */}
//     </div>
//   );
// }


export default function Home({ products }) {

  const router = useRouter();
  // const now = 60;
  // const time = new Date();
  // time.setSeconds(time.getSeconds() + 600); // 10 minutes timer
  // // console.log(new Date())

  // const prevRef = useRef(null);
  // const nextRef = useRef(null);

  return (
    <>
      <Head>
        <title>{"TooFav Online Shopping"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='pageWraper'>

      <section className='main-banner'>
        <div class="container-fluid">
        <MainBanner/>
        </div>
      </section>

      <section className='category-carousel'>
        <div class="container-fluid">
        <Swiper
          // install Swiper modules
          modules={[A11y]}
          spaceBetween={20}
          slidesPerView={4}
          breakpoints={{
            640: {
              slidesPerView: 4,
              spaceBetween: 20,
            },
            768: {
              slidesPerView: 7,
              spaceBetween: 20,
            },
            1024: {
              slidesPerView: 12,
              spaceBetween: 20,
            },
          }}
          // navigation
          // pagination={{ clickable: true }}
          // scrollbar={{ draggable: true }}
          // onSwiper={(swiper) => console.log(swiper)}
          // onSlideChange={() => console.log('slide change')}
        >
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div class="cate-item">
            <Link href="/product">
              <div class="img-area">
                <Image
                  className='bg-image'
                  src="/canon-r5-58407008.jpg"
                  alt="Banner image"
                  width={110}
                  height={110}
                />
                <img src='/camera-01.svg' class="icon-img"/>
              </div>
              <h4 class="cate-name">Electronics</h4>
              </Link>
            </div>
          </SwiperSlide>
        </Swiper>
        </div>
      </section>

      <section class="three-sections-home">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-4">
                <div class="col-widget deals-day">
                  <h4 class="widget-title">Deals of the Day</h4>
                  <div class="row">
                    <div class="col-lg-6 col-6">
                      <div class="deals-card">
                        <div class="img-area">
                          <Image
                            className='deal-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="price">
                          <strike>₹ 1499.99</strike>
                          <span class="cur-price">₹ 1499.99</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-6 col-6">
                      <div class="deals-card">
                        <div class="img-area">
                          <Image
                            className='deal-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="price">
                          <strike>₹ 1499.99</strike>
                          <span class="cur-price">₹ 1499.99</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-6 col-6">
                      <div class="deals-card">
                        <div class="img-area">
                          <Image
                            className='deal-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="price">
                          <strike>₹ 1499.99</strike>
                          <span class="cur-price">₹ 1499.99</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-6 col-6">
                      <div class="deals-card">
                        <div class="img-area">
                          <Image
                            className='deal-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="price">
                          <strike>₹ 1499.99</strike>
                          <span class="cur-price">₹ 1499.99</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="col-widget offer-min-banner">
                  {/* <h4 class="widget-title">Deals of the Day</h4> */}
                  <div class="row">
                    <div class="col-lg-12">
                      <div class="offer-card">
                        <div class="img-area">
                          <Image
                            className='offer-image'
                            src="/1920_750_29894mensxp-fragrances 1.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-12">
                      <div class="offer-card">
                        <div class="img-area">
                          <Image
                            className='offer-image'
                            src="/1920_750_29894mensxp-fragrances 1.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="col-widget deals-day left-of-area">
                  <h4 class="widget-title">Pickup where you left off</h4>
                  <div class="row">
                    <div class="col-lg-4  col-4">
                      <div class="left-of-card">
                        <div class="img-area">
                          <Image
                            className='pro-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="product-nam">
                          Matuki Designer Studio Women Kurta And Pant Set
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4  col-4">
                      <div class="left-of-card">
                        <div class="img-area">
                          <Image
                            className='pro-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="product-nam">
                          Matuki Designer Studio Women Kurta And Pant Set
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4  col-4">
                      <div class="left-of-card">
                        <div class="img-area">
                          <Image
                            className='pro-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="product-nam">
                          Matuki Designer Studio Women Kurta And Pant Set
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4  col-4">
                      <div class="left-of-card">
                        <div class="img-area">
                          <Image
                            className='pro-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="product-nam">
                          Matuki Designer Studio Women Kurta And Pant Set
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4  col-4">
                      <div class="left-of-card">
                        <div class="img-area">
                          <Image
                            className='pro-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="product-nam">
                          Matuki Designer Studio Women Kurta And Pant Set
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4  col-4">
                      <div class="left-of-card">
                        <div class="img-area">
                          <Image
                            className='pro-image'
                            src="/canon-r5-58407008.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                        <div class="product-nam">
                          Matuki Designer Studio Women Kurta And Pant Set
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </section>

      <section class="falshpro-carousel">
        <div class="container-fluid">
          <ProductCarousel itemCount={8} flashsale caroselTitle={"Flash Sale"}/>
        </div>
      </section>


      <section class="newarrival-carousel">
        <div class="container-fluid">
          <ProductCarousel products itemCount={8} caroselTitle={"New Arrivals"}/>
        </div>
      </section>



      <section class="offer-mini-banner-3">
        <div class="container-fluid">
          <div class="row">
              <div class="col-md-4">
                <div class="col-widget">
                    <div class="offer-card">
                        <div class="img-area">
                          <Image
                            className='offer-image'
                            src="/1920_750_29894mensxp-fragrances 1.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                    </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="col-widget">
                    <div class="offer-card">
                        <div class="img-area">
                          <Image
                            className='offer-image'
                            src="/1920_750_29894mensxp-fragrances 1.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                    </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="col-widget">
                    <div class="offer-card">
                        <div class="img-area">
                          <Image
                            className='offer-image'
                            src="/1920_750_29894mensxp-fragrances 1.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
                    </div>
                </div>
              </div>
            </div>
        </div>
      </section>

      <section class="prdct-ban-sldr">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-4 col-lg-3">
                        <div class="vertic-img-area">
                          <Image
                            className='offer-image'
                            src="/banner-0215848-vertc.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
              </div>
              <div class="col-md-8 col-lg-9">
                <ProductCarousel  itemCount={6}  caroselTitle={"Fashion"}/>
              </div>
            </div>
          </div>
      </section>


      <section class="prdct-ban-sldr">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-4 col-lg-3 order-md-2">
                        <div class="vertic-img-area">
                          <Image
                            className='offer-image'
                            src="/banner-0215848-vertc.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
              </div>
              <div class="col-md-8 col-lg-9 order-md-1">
                <ProductCarousel  itemCount={6} caroselTitle={"Electronics"}/>
              </div>
            </div>
          </div>
      </section>

      <section class="prdct-ban-sldr">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-4 col-lg-3">
                        <div class="vertic-img-area">
                          <Image
                            className='offer-image'
                            src="/banner-0215848-vertc.jpg"
                            alt="Deals image"
                            fill
                          />
                        </div>
              </div>
              <div class="col-md-8 col-lg-9">
                <ProductCarousel itemCount={6} caroselTitle={"Appliances "}/>
              </div>
            </div>
          </div>
      </section>

      <section class="sitemap-links">
          <div class="container-fluid">
            <ul class="nav">
                <li class="nav-item">
                    <b>MOST SEARCHED FOR ON TOOFAV</b>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
            </ul>
            <ul class="nav">
                <li class="nav-item">
                    <b>MOST SEARCHED FOR ON TOOFAV</b>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
            </ul>
            <ul class="nav">
                <li class="nav-item">
                    <b>MOST SEARCHED FOR ON TOOFAV</b>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">GoPro Action Camera</a>
                </li>
            </ul>
          </div>
      </section>


      {/* {products.map((product) => {
          return (
            <div key={product.id}>
                <ProductItemCard product={product}/>
            </div>
          )
      })} */}


        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div> */}

        {/* <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div> */}

        {/* <div className={poppins.className}>
          <Link className={styles.card} href='/about'>About Us</Link>
          <Link className={styles.card} href='/docs'>Docs</Link>
          <Link className={styles.card} href='/product'>Products</Link>
          <Link className={styles.card} href='/shop'>Shop</Link>
          <Link className={styles.card} href='/users'>Users</Link>
          <Link className={styles.card} href='/posts'>Posts</Link>
        </div> */}

        

        {/* <div className={poppins.className}>
          <button onClick={handleClick}>Place Order</button>
        </div> */}

        {/* <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={poppins.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={poppins.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={poppins.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={poppins.className}>
              Learn about Next.js in an poppinsactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={poppins.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={poppins.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={poppins.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={poppins.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  )
}

// export async function getStaticProps() {
//   // Call an external API endpoint to get posts.
//   // You can use any data fetching library
//   // const res = await fetch('https://jsonplaceholder.typicode.com/users')
//   // const data = await res.json()

//   // By returning { props: { posts } }, the Blog component
//   // will receive `posts` as a prop at build time
//   return {
//     props: {
//       // products,
//     },
//   }
// }

export async function getServerSideProps(context){
  const {params} = context
  const res = await fetch("https://jsonplaceholder.typicode.com/posts")
  const data = await res.json()

  return{
      props: {
          products: data.slice(0, 15),
          // countItem,
      }
  }
}